### ISSUE TITLE
slow network filesystem access ?

### ISSUE THREAD

**Issue by strk** [OSGeo/shapelib#2]
It was reported by a PostGIS user, who provided a patch for our copy of shapelib:
https://git.osgeo.org/gitea/postgis/postgis/pulls/40

**Comment by rouault** [comment]
Interesting. I'd note the patch should probably be modified for upstream inclusion as it assumes a write-only usage of shapelib, but as shapelib can also have read/update scenarios, the user for example can read shape N, and then write shape N + 1. So when transitionning between read and write, a seek() is needed for conformance with Posix I/O (I remember bugs in some GDAL drivers on BSD systems due to this)

**Comment by dfuhry** [comment]
Hi Even, thank you for the comments. I rewrote the patch more generally for shapelib and submitted PR #3. To address mixed read/update scenarios you mention, in the second of the two commits there, I added a DBFInfo bRequireNextWriteSeek flag to have DBFFlushRecord always seek when in doubt, including after a DBFLoadRecord call.
Please let me know if you have any questions or think any parts would be better done differently.

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/shapelib/pull/3
